[project]
name = "miminions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=38.2.0",
    "fastmcp>=2.12.4",
    "openai-agents>=0.3.3",
    "pydantic-ai>=1.27.0",
]
