[project]
name = "miminions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.12.4",
    "openai-agents>=0.3.3",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
